#!/bin/sh
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
export root="${IPKG_INSTROOT}"
export pkgname="${APK_PACKAGE}"
default_prerm
if [ -z "${IPKG_INSTROOT}" ]; then
    /etc/init.d/ddns stop
fi
exit 0
